version: '2'
services:
    evesmarttrader-elasticsearch:
        container_name: evesmarttrader-elasticsearch
        image: elasticsearch:1.7.5
        # volumes:
        #     - ~/volumes/jhipster/EveSmartTrader/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
